'use strict';
const assert = require('node:assert/strict');
const test = require('node:test');
const S = require('../site/state.js');
const course = {id: 'test-course', modules: [{id: 'L00', track:'core', checkpoints:[{id:'build'}, {id:'explain'}]}, {id:'L01', track:'optional', checkpoints:[{id:'extra'}]}]};
const mod = course.modules[0], now = Date.UTC(2026, 9, 9);
function finished() { let p=S.blank(course); p=S.change(p,mod,'build',true,now); p=S.change(p,mod,'explain',true,now); return S.change(p,mod,'selfTest',true,now); }
test('blank state and core-only statistics',()=>assert.deepEqual(S.stats(S.blank(course),course),{finished:0,core:1,checked:0,total:3,percent:0}));
test('checklists require a separate self-assessment; writes are immutable',()=>{const old=S.blank(course);let p=S.change(old,mod,'build',true,now);p=S.change(p,mod,'explain',true,now);assert.equal(S.complete(S.getModule(p,'L00'),mod),false);assert.deepEqual(old.modules,{});assert.equal(S.complete(finished().modules.L00,mod),true);});
test('completion schedules local reviews on days 1, 3, 7 and 21',()=>{let p=finished();assert.equal(p.modules.L00.review.dueAt,new Date(now+S.DAY).toISOString());p=S.review(p,mod,now);assert.equal(p.modules.L00.review.step,0);p=S.review(p,mod,now+S.DAY);assert.equal(p.modules.L00.review.dueAt,new Date(now+3*S.DAY).toISOString());p=S.review(p,mod,now+3*S.DAY);assert.equal(p.modules.L00.review.dueAt,new Date(now+7*S.DAY).toISOString());p=S.review(p,mod,now+7*S.DAY);assert.equal(p.modules.L00.review.dueAt,new Date(now+21*S.DAY).toISOString());p=S.review(p,mod,now+21*S.DAY);assert.equal(p.modules.L00.review.dueAt,null);assert.equal(p.modules.L00.review.step,4);assert.deepEqual(S.validate(p,course),p);});
test('late reviews preserve spacing rather than enabling four immediate confirmations',()=>{let p=S.review(finished(),mod,now+30*S.DAY);assert.equal(p.modules.L00.review.dueAt,new Date(now+32*S.DAY).toISOString());p=S.review(p,mod,now+30*S.DAY);assert.equal(p.modules.L00.review.step,1);});
test('undo completion also resets associated review schedule',()=>{const p=S.change(finished(),mod,'build',false,now);assert.equal(p.modules.L00.completedAt,null);assert.equal(p.modules.L00.review,null);});
test('export / import round trip',()=>{const p=finished();assert.deepEqual(S.validate(JSON.stringify({...p,exportedAt:new Date(now).toISOString()}),course),p);});
test('reject malformed, oversized, older and newer versions without changing state',()=>{const p=finished();for(const bad of ['!', 'x'.repeat(S.MAX_BYTES+1), {...p,version:0}, {...p,version:2}, {...p,courseId:'other'}, {...p,modules:[]}, {...p,modules:{L99:p.modules.L00}}])assert.throws(()=>S.validate(bad,course));assert.equal(p.modules.L00.selfTest,true);});
test('reject unknown checkpoints, duplicates, dates and inconsistent completion',()=>{for(const alter of [{checks:['<img src=x onerror=alert(1)>']},{checks:['build','build']},{completedAt:'yesterday'},{selfTest:false},{review:null},{review:{step:99,dueAt:null,lastAt:null}}]){const p=finished();Object.assign(p.modules.L00,alter);assert.throws(()=>S.validate(p,course));}});
test('drop extra imported properties; do not retain arbitrary HTML data',()=>{const p=finished();p.evil='<script>evil</script>';p.modules.L00.notes='<img onerror=evil>';const clean=S.validate(p,course);assert.equal(Object.hasOwn(clean,'evil'),false);assert.equal(Object.hasOwn(clean.modules.L00,'notes'),false);});
test('prototype-looking module names rejected',()=>{const p=JSON.stringify(S.blank(course)).replace('"modules":{}','"modules":{"__proto__":{}}');assert.throws(()=>S.validate(p,course));});
test('due reviews and finished core counts',()=>{const p=finished();assert.equal(S.due(p,course,now).length,0);assert.equal(S.due(p,course,now+S.DAY).length,1);assert.equal(S.stats(p,course).percent,100);});
